### PR TITLE
Replace uvtools with hera_filters

### PR DESCRIPTION
**Pull request by tyler-a-cox**
The filtering code in `uvtools` was recently moved into its own repository, `hera_filters`. I replaced all instances of `uvtools` with `hera_filters`

### CODE REVIEW

**Review by aewallwi — CHANGES_REQUESTED** [review]
Thanks for all the hard work getting this converted @tyler-a-cox . The only general comment I have is that for some reason the `HAVE_UVTOOLS` equivalent lines are now no longer covered by tests. Any idea why this is (in other words, how were the `HAVE_UVTOOLS` lines covered in the first place?) If this is too much of a dive into testing esoterica I'm in favor of just making `hera_filters` a dependancy of `hera_cal` and just dispensing of these lines -- much of the core functionality in `hera_cal` relies on `hera_filters` and the `hera_filters` dependencies are minimal (or at least smaller then other dependancies like `hera_qm`) Let me know if you are in favor of one path or the other.

**Comment by tyler-a-cox** [comment]
I lost track of this one for a while. @aewallwi, I decided to make `hera_filters` a dependency, since it doesn't rely on any additional libraries `hera_cal` isn't already using. I did pin the numpy version for testing since one `redcal` test fails on linux as noted here https://github.com/HERA-Team/hera_cal/issues/812. We should probably figure out what's causing that failure, but for now this fixes the error.

**Review by aewallwi — APPROVED** [review]
Looks good too me.

**Comment by tyler-a-cox** [comment]
@jsdillon, I don't think it's been added yet. I'll work on adding it this morning.

**Comment by jsdillon** [comment]
Ok, let's do that. @steven-murray is the maestro for this

**Comment by tyler-a-cox** [comment]
Great, I'll check in with him.

**Pull request merged**
