### PR TITLE
initialize clean_info as a dict, not as a DataContainer

### PR DESCRIPTION
**Pull request by jsdillon**

### CODE REVIEW

**Comment by jsdillon** [comment]
@adampbeardsley can you test this branch and see if it fixes your problem?

**Comment by jsdillon** [comment]
All the other objects are visibilities, so conjugating them if you ask for the conjugate key is the right thing to do.

**Comment by adampbeardsley** [comment]
Oh, I just saw what I was missing - Line 132 of `datacontainer.py` conjugates _and_ reverses the key. Ok, that part makes sense.

**Comment by jsdillon** [comment]
For posterity: this was related to this thread: https://eoranalysis.slack.com/archives/C65UTUHPG/p1548291055052400

**Pull request merged**
