### PR TITLE
Update get_reds to include clearer position tolerance and ex_ants functionality.

### PR DESCRIPTION
**Pull request by jsdillon**
This PR addresses #134.

### CODE REVIEW

**Comment by nkern** [comment]
this looks great, and its fast! one thing is that the `get_pos_reds` returns antenna pairs with (hi, low) ordering sometimes and (low, hi) ordering. It seems standard to stick to (low, hi) ordering.

**Comment by jsdillon** [comment]
By design, all baseline pairs in a group should have the same orientation. I think this is really useful, personally. The documentation says how the orientation is selected, though there was a typo which I've fixed.

**Comment by jsdillon** [comment]
I could add a default=False keyword argument to get_pos_reds to do it differently if you'd find that useful.

**Comment by nkern** [comment]
I think all baselines can have the same orientation, and still have all keys (low, hi), no? its just that in our UVData objects, I think all the baselines are (low, hi) format...

**Comment by nkern** [comment]
this looks great. thanks for adding in low_hi capability. i'm ready to merge this whenever possible

**Pull request merged**
