### PR TITLE
make sure that kwargs are passed.

### PR DESCRIPTION
**Pull request by aewallwi**
ensure that some kwargs that were being dropped by frf updates are in fact passed correctly.

### CODE REVIEW

**Comment by jsdillon** [comment]
Tests are failing...

**Comment by aewallwi** [comment]
should be fixed now.

**Comment by jsdillon** [comment]
Looks like there are some merge conflicts.

Also, to be clear, are we eliminating these arguments or just grouping them in `**kwargs`?

**Comment by aewallwi** [comment]
> 

That's correct, we are moving explicit args into kwargs when possible (to avoid confusion). I think all of the conflicts should be taken care of now.

**Review by jsdillon — APPROVED** [review]
Looks good to me.

**Pull request merged**
