### PR TITLE
GitHub ci update

### PR DESCRIPTION
**Pull request by mkolopanis**
some general updates to the github action ci yaml.

Uses an action to setup the conda env rather than the old clunky bash script.
~~makes an empty directory to execute the tests in, this actually tests the installed version of hera_cal and breaks a degeneracy in the namespace between installed and cloned repo.~~ this was getting too complicated because of how test_utils is set up.

### CODE REVIEW

**Comment by mkolopanis** [comment]
@jsdillon @aewallwi  made some tidy up changes for your github actions yaml if you'd like to take a look. There's an action specifically to download and install via mini-conda that I have found quite convenient in other projects.

**Review by aewallwi — CHANGES_REQUESTED** [review]
Thanks for streamlinging things @mkolopanis ! Would it be possible to include a link to documentation of the features being used in the conversation or inline comments? Other then that, I think this basically looks good to go.

**Comment by mkolopanis** [comment]
I think I'm a little confused by the request here. Are you wanting a link to https://github.com/marketplace/actions/setup-miniconda in the yaml?

**Comment by aewallwi** [comment]
> I think I'm a little confused by the request here. Are you wanting a link to https://github.com/marketplace/actions/setup-miniconda in the yaml?

I think just pasting it in the conversation is sufficient! Thanks. I've approved.

**Review by aewallwi — APPROVED** [review]

**Pull request merged**
