### PR TITLE
fix some things that will error in pyuvdata 3.0

### PR DESCRIPTION
**Pull request by bhazelton**
This future proofs for pyuvdata v3.0 which is coming soonish.

### CODE REVIEW

**Comment by jsdillon** [comment]
This PR is failing a bunch of tests... do we expect it to pass before pyuvdata 3.0?

**Comment by bhazelton** [comment]
Sigh. I though it would but I forgot that I fixed the spelling of the `flags_array` to `flag_array` in `write_uvh5_part` because it didn't match the spelling throughout the rest of the code base. I'll fix it to work now and in the future, it'll just be a little clunky.

**Review by jsdillon — APPROVED** [review]
That all looks good to me. If you don't mind adding an issue to remove that reference to the pyuvdata version... eventually, I'm sure we'll require v3.0 or later, at which point we can remove that hacky bit.

**Comment by bhazelton** [comment]
Ok, I made the issue. What do you want to do about the code coverage? I can add a `pragma: no cover` to the code branch for pyuvdata > 3.0 if you like. The other line was apparently already not covered, I just made the syntax pep8 compliant.

**Comment by jsdillon** [comment]
I can live with the tiny decrease in coverage.

**Pull request merged**
