### PR TITLE
Fix np comparisons

### PR DESCRIPTION
**Pull request by anguta**
Fix issue where `np.testing.assert_array_equal` was being applied to scalars which is no longer allowed. To address this, I've changed comparisons between arrays in scalars of the form `np.testing.assert_array_equal(array, scalar)` to `np.testing.assert_array_equal(array, np.ones_like(array) * scalar)`  or, when appropriate `np.zeros_like` in place of `np.ones_like`.

### CODE REVIEW

**Comment by jsdillon** [comment]
Are you sure this isn't allowed? The documentation says it's fine: https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_equal.html

**Comment by anguta** [comment]
> Are you sure this isn't allowed? The documentation says it's fine: https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_array_equal.html

I see. I was under the impression that this was causing the macos python 3.7 test to fail in #674 but this may not be the case.

**Comment by jsdillon** [comment]
Looks like that PR is passing its tests... Should we close this one?

**Comment by plaplant** [comment]
@anguta as I said on #674, I believe the tests were failing before because of linsolve + numpy v1.20 incompatibilities that have since been fixed. I don't know if we need to make these changes, unless tests are still failing.

**Comment by anguta** [comment]
It looks like all the test now pass on #674 (after rebasing). Thanks @plaplant (sorry I missed your comment). I will close this PR.

**Pull request closed without merging**
