### PR TITLE
added "get_antpos" function to utils.py w/ tests

### PR DESCRIPTION
**Pull request by nkern**
I wrote this script for myself and i'm finding I'm using it a lot, so I figured other people would benefit from this. should be a quick & easy review

### CODE REVIEW

**Comment by jsdillon** [comment]
Shouldn't this be in pyuvdata?

**Comment by nkern** [comment]
yeah could be.. there are a few functions like this one in `hera_cal` (`get_aa_from_uv` and `UVData_to_dict`), so its not clear to me exactly what belongs in `pyuvdata` and what is just being swept into `hera_cal`...

**Comment by jsdillon** [comment]
Yeah...I'm not 100% sure either. Curious what @bhazelton thinks.

**Comment by bhazelton** [comment]
I'm not at all opposed to adding it to pyuvdata as a method on the uvdata instance. I think other people are more likely to find it and use it there. But I think you should come up with a slightly more clear name for the function.

**Comment by nkern** [comment]
ok, i'll make a PR on pyuvdata then!

**Pull request closed without merging**
