### PR TITLE
Make datacontainer polarization case insensitive

### PR DESCRIPTION
**Pull request by jsdillon**
This addresses #171

### CODE REVIEW

**Comment by nkern** [comment]
this should pass once we merge in the `cal_formats_fix` PR

**Comment by jsdillon** [comment]
@nkern oh, good...do you need any help on that PR or are you good?

Also, do you want to review this PR?

**Comment by nkern** [comment]
that PR just got merged in . sure i can review this. if you can update your local master and rebase this on top of that I'll be happy to merge this once i review it

**Comment by jsdillon** [comment]
Updated DataContainer documentation to address #173 

@anguta wanna take a look?

**Pull request merged**
